language: node_js
dist: trusty
node_js:
  - "7"
# S: Build Lifecycle
install:
  - npm install hexo-cli -g
  - npm install

#before_script:
 # - npm install -g gulp
#node genmd.js

script:
#- node genmd.js
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "lirawx"
  - git config user.email "lira_wx@outlook.com"
  - git add .
  - git commit -a -m "Update posts"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/lirawx/lirawx.github.io.git
