author: lirawx. # 作者
description: lirawx.'s blog
keyword: life is short,let it be undefined;
favicon:

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# gitment
gitment_oauth_id: 2950d853073141b661e3
gitment_oauth_secret: 2e07409146f34c725268ea45530c7a2d3364fe04
gitment_owner: lirawx
gitment_repo: lirawx.github.io




# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

# website track.
baidu_id: 9d96dd222ca2ed3fec333e0f5fa70590
google_ga_id: UA-80549073-1

about:
  banner:
  avatar: https://avatars1.githubusercontent.com/u/10678334?v=4&u=932ea384b1c8a6136bf9a243dcf2f5867071164d&s=400
  description: life is short,let it be undefined;
